mangaki/mangaki/templates/.editorconfig, mangaki/mangaki/templates/mangaki/manga_detail.html
L'idée étant d'employer le même markup que celui qui est employé par les anime.
Cependant, je pense qu'il est possible de refactoriser ça dans un work_base.html, mais je n'ai pas assez de connaissance avec les réferences que les anime utilisent pour démarrer cette refacto.
Dans l'immédiat, on peut se permettre cette *cheap* modification.
=> Rendre l'UI de la page manga plus consistente

mangaki/mangaki/templates/mangaki/anime_list.html
This reverts commit cc586a07b9b4af62d597233fb42f75fcd9fdd061.
It is no longer Satoshi Kon's birthday.
=> Revert "Happy Birthday Satoshi Kon!"

mangaki/mangaki/static/js/autocomplete.js, mangaki/mangaki/static/js/vote.js
En JavaScript, == effectue une comparaison sans prendre en compte le
type et suivant des règles alambiquées. Par exemple, `0 == ‘0’`, `0 ==
[]`, et `’0’ != []` sont tous les trois vrais en JavaScript.
Utiliser === (et !== respectivement) permet de forcer un résultat faux
si le type des valeurs comparées (par exemple un entier et une chaîne
de caractères) sont différents, et est généralement conseillé pour
diverses raisons.
Ce patch remplace dont l’utilisation de == et != par === et !==
respectivement dans le code JavaScript de Mangaki.
PR proposée après discussion avec @RaitoBezarius dans #49.
=> Utilise === au lieu de == dans les fichiers .js

mangaki/irl/models.py
Actuellement, Mangaki affiche un “None” disgracieux dans le bandeau
d’événement pour les événements sans lieu ni chaîne de diffusion (par
exemple, sortie nationale d’un film - http://mangaki.fr/anime/10013). Ce patch enlève ce “None”.
=> Ne pas afficher “None” pour les événements sans lieu

mangaki/mangaki/admin.py, mangaki/mangaki/models.py
Cette page ne permet pas d'ajouter manuellement un nouveau top N (il faut le faire via `manage.py top`), mais seulement de voir la liste, de modifier les rankings, et de supprimer le top généré un certain jour en cas de besoin.
=> Ajoute une page d’admin rudimentaire pour les tops

mangaki/mangaki/static/js/vote.js, mangaki/mangaki/templates/base.html, mangaki/mangaki/templates/mangaki/anime_list.html, mangaki/mangaki/templates/mangaki/manga_list.html
Actuellement, lorsqu'un utilisateur se connecte ou créé un compte, il
est redirigé vers la page d’accueil de Mangaki. Ce patch fait en sorte
qu’il soit redirigé vers la page où il était avant de se connecter à
la place.
=> Redirige vers la page actuelle apres connexion

mangaki/mangaki/views.py
Actuellement lors de l'affichage d'un Top 20, on effectue une requête par artiste. Puisque l'on sait que l'on va tous les afficher de toute facon, il vaut mieux faire une unique requête pour tous les récupérer d'un coup.
=> Effectue une unique requete pour les objets dans un Top

mangaki/mangaki/static/css/skin.css, mangaki/mangaki/static/js/skin.js, mangaki/mangaki/static/js/vote.js, mangaki/mangaki/templates/mangaki/anime_detail.html, mangaki/mangaki/templates/mangaki/anime_list.html, mangaki/mangaki/templates/mangaki/manga_detail.html, mangaki/mangaki/templates/mangaki/manga_list.html, mangaki/mangaki/templates/mangaki/reco_list.html, mangaki/mangaki/templates/work_poster.html, mangaki/mangaki/templates/work_rating.html, mangaki/mangaki/views.py
Afin de rendre plus lisible la mosaïque, ce patch introduit 3
changements :
- Les votes sont maintenant plus proches du poster, et “grandissent”
vers la gauche (par-dessus le poster auquel ils correspondent).
- Le nom de l’oeuvre est maintenant en-dessous, et plus au-dessus
- Une fine bordure relie le nom de l’oeuvre à son poster pour éviter
toute ambigüité
Quelques exemples des différences (je n'ai pas testé sur mobile, mais j'ai testé en réduisant la taille de la fenêtre de mon navigateur) :
| Avant | Après
----|------|----------
Taille maximale | <img width="617" alt="screen shot 2016-01-21 at 11 38 28" src="https://cloud.githubusercontent.com/assets/146210/12478201/da35a57e-c033-11e5-8c00-0acb23ebc0b7.png"> | <img width="601" alt="screen shot 2016-01-21 at 11 38 19" …
=> Clarifie l’affichage de la mosaïque

mangaki/mangaki/templates/base.html
Lien vers la page de profil mis sur le nom utilisateur si loggué pour éviter d'avoir un lien ne renvoyant vers rien 
fixes #74
=> Link on the username when logged in

mangaki/mangaki/templates/work_rating.html
Fixe une taille maximale des titres à 50 caractères dans les templates work_rating
fixes #82
=> Title too long, max length 50 in template

mangaki/mangaki/static/js/vote.js
Lorsque `vote.js` change une carte "Chargement..." par la vraie carte d'une oeuvre, change aussi le alt-text au cas où l'image ne charge pas.
=> Mets à jour l'attribut alt du poster dans vote.js

mangaki/mangaki/templates/pagination.html
This is a quick fix for #124; in the long term the more appropriate
fix would probably be to keep `pagination.html` clean and instead have
a different route for each of the sort modes, e.g. `/anime/popular/`
etc.
Fixes #124.
=> Keep the ?sort parameter when paginating

mangaki/mangaki/static/js/vote.js, mangaki/mangaki/templates/work_rating.html
This makes it so that we leave the "Loading" card when no actual card can be found on the server in the mosaic. Moreover, we try harder to not be in that situation by loading cards from different positions if the current position doesn't have any card.
This is not a situation that would happen in practice on the actual server, but it can happen easily with the small seed and make browsers hang with the current implementation.
=> Fix infinite loading in vote.js

mangaki/mangaki/settings.py, mangaki/mangaki/templates/base.html, requirements.txt
C'était facile, il existe un package pour ça : https://pypi.python.org/pypi/django-cookie-law/1.0.7
Fixes #142.
=> Add cookie law banner

mangaki/mangaki/views.py
Fixes #66.
Ceci fait en sorte que `/{anime,work,manga,album}/ID` redirigent tous vers `/anime/ID` si c'est un anime, `/manga/ID` si c'est un manga, etc.
C'est une décision arbitraire pour #66 qui pourra être changé dans le futur, mais c'est pas très important en vrai.
=> Canonicalize work URLs

mangaki/mangaki/static/css/typeahead.css
Fixes #143.
Not sure of the original purpose of this code. `links-examples` is used nowhere in Mangaki.
=> Unhide search bar on narrow screens

mangaki/mangaki/management/commands/compare.py, mangaki/mangaki/utils/nmf.py, mangaki/mangaki/utils/svd.py, mangaki/mangaki/utils/values.py
Here is the non-negative matrix factorization, directly from scikit-learn, that allows more interpretable components. By definition, it approximates a non-negative matrix, so I decided to put a rating of 1 for like/favorite and 0 for the rest. Thus, it does not consider dislikes, it just tries to put together things people like.
The corresponding error values:
[ALS] 0.436 (still the best)
[NMF] 0.530
[ZERO] 0.649
[SVD] 0.761 (worse than the dumb algorithm saying 0 all the time)
(I should remove willsee and wontsee from the test set though :D)
BTW, there is a [sparseness parameter](http://scikit-learn.org/stable/modules/generated/sklearn.decomposition.NMF.html) in the scikit-learn implementation!
=> Add NMF for topic extraction

mangaki/mangaki/discourse.py, mangaki/mangaki/settings.py
Local development environment shouldn't require discourse for e.g. viewing a user's profile page.
=> Do not require discourse settings for avatar initialization

mangaki/mangaki/__init__.py, mangaki/mangaki/apps.py, mangaki/mangaki/factories.py, mangaki/mangaki/models.py, mangaki/mangaki/receivers.py, mangaki/mangaki/tests/test_user.py, mangaki/mangaki/views.py
- We no longer use a post_save signal for updating scores when a Suggestion is
changed; rather this has its place directly in the Suggestion.save method.
- Signals are connected in the ready() method of Mangaki's new application
configuration class, as recommended by Django's documentation:
https://docs.djangoproject.com/en/dev/topics/signals/#connecting-receiver-functions
Note that we use a receivers module instead of a signals module to allow for
the creation and import of custom signals without registering handlers if
the need ever arises.
- Profile creation is no longer tied to login with django-allauth but rather
to the actual User model creation. This helps handling corner cases such as
accounts created through the `manage.py createsuperuser` management command
actually having a …
=> Clean up signal handling

circle.yml
CodeCov tool must run in the project root folder in order for the website UI to work.
Yes, it's strange, but we have to comply.
=> Fix CodeCov UI when browsing files coverage

circle.yml
Actually:
- We were not using the `.coverage` configuration to ignore migrations, etc…
- Codecov could not look up the path put in the reports uploaded to their servers.
I think this should finally fix these problems.
=> Code coverage is now browsable on the codecov website

requirements/dev.txt, requirements/production.txt
Due to DPP recent introduction on `master`.
=> Move Pandas, sklearn, SciPy to production requirements

mangaki/mangaki/settings.py, mangaki/mangaki/views.py
This is a first step towards the resolution of #59. It allows
anonymous users to rate works, and keeps the state of the rated works
across consecutive page loads in Django's session.
For now, the usage of this information is limited: although anonymous
user can rate works, they cannot get recommendations from those
ratings, transfer them to a new or existing account, etc. Support for
these will come in subsequent patches.
=> Enable anonymous user to rate works

mangaki/mangaki/tests/test_reco.py, mangaki/mangaki/tests/test_user.py, mangaki/mangaki/utils/algo.py, mangaki/mangaki/utils/common.py, mangaki/mangaki/utils/data.py, mangaki/mangaki/utils/recommendations.py, mangaki/mangaki/utils/wals.py
Dans la foulée j'ai vraiment cru que je pourrais faire un test de la route recommandation mais c'est galère parce qu'il faut :
- ajouter des œuvres bidon pour les recommandations, avec leurs ratings
- gérer le cas où un objet Pickle est déjà enregistré ou pas
En plus du coup ça va ralentir les tests. Notez qu'on peut juste tester MangakiZero, mais faut quand même les œuvres bidon.
=> Fix path of pickle files (broken so far)

mangaki/mangaki/management/commands/fit_algo.py, mangaki/mangaki/templates/base.html, mangaki/mangaki/utils/algo.py, mangaki/mangaki/utils/data.py, mangaki/mangaki/utils/ratings.py, mangaki/mangaki/utils/recommendations.py, mangaki/mangaki/views.py
This is a second step towards the resolution of #59. It allows
anonymous users to get recommendations (using the KNN algorithm only,
since we do not have trained models for them).
This is implemented by making the various algorithms take directly a
list or (user_id, work_id, choice) triplets instead of building those
from a queryset, as well as some glue to add the relevant triplets
from anonymous users at the interface between the database and the
algorithms themselves.
=> Enable anonymous users to get recommendations

mangaki/mangaki/views.py
Too many duplicated queries were done to fetch categories during `get_profile`.
=> Fix performance issue when going on /u/{someone} with a lots of ratings

requirements/production.txt
Looks like we are not using any (broken things)[https://docs.djangoproject.com/en/1.11/releases/1.11/#backwards-incompatible-changes-in-1-11] in Django 1.11, although I only did a simple test with a local `runserver`.
=> Upgrade to Django 1.11

mangaki/mangaki/utils/recommendations.py
Previously, we were using 0 for the identifier of an anonymous user,
except that it made us use a `current_user_id` variable for tracking
that and it was easy to just use (erroneously) `request.user.id`
instead.
Since there actually are no requirements on `current_user_id` being a
numeric value, this patch makes it so that we use `None` instead, since
that is the value of `user.id` for an anonymous user, and removes
`current_user_id` altogether.
Fixes #317.
=> Use None instead of 0 for anonymous user identifier.

mangaki/mangaki/templatetags/anonymous_ratings.py
While we keep them until the session ends for technical reasons, they
shouldn't be shown.
=> Non-anonymous users don't have anonymous ratings

mangaki/mangaki/templates/profile.html, mangaki/mangaki/views.py
Minimal PR (+6 –2 lines) that should be merged asap.
Also fix the stupid bug: nobody can browse their own profile if private.
Raises the following question: should anyone sort any wishlist, or only theirs? Anyway, if a profile is public, it can be simulated by anyone, using a fake account, in order to see what Mangaki would recommend.
=> Add link in profile for sorting any wishlist

mangaki/mangaki/utils/wals.py
TensorFlow is only required by the WALS algorithm, and loading the
library has a prohibitive overhead on lower-powered devices. Let's only
load it when the WALS algorithm is needed, which for now is only when
running the algorithm, which shouldn't be done on the webserver anyways.
=> Only require tensorflow when needed

mangaki/.gitignore, requirements/dev.txt
- Bump Django Debug Toolbar to 1.8, read [the changelog here](https://github.com/jazzband/django-debug-toolbar/blob/master/docs/changes.rst).
- Add `/build` and `/dist` to ignored directories when packaging Mangaki, those will appear and may mess with your search tools (e.g. `ag`) or whatever.
=> House-keeping of gitignore and dependencies

mangaki/mangaki/tests/test_posters.py, mangaki/mangaki/utils/db.py, mangaki/mangaki/utils/mal.py
Due to the refactor of MAL introduced in #301 — `get_potential_poster` got broken (signature of `search_work` was incorrect).
This is fixed in this PR, with a test to prevent future regressions.
=> [Hotfix] Make posters refreshable once again (fix get_potential_poster)

mangaki/mangaki/settings.py, mangaki/mangaki/tests/test_anilist.py, mangaki/mangaki/wrappers/anilist.py, mangaki/settings.template.ini
Adds an API wrapper for AniList's API (see issue #343). In this PR, only basic operations are implemented :
- AniList settings in `settings.ini`
- Authenticate to AniList
- Check that the AniList's API token is still valid
- Make requests to the API
=> Add an AniList's API wrapper

mangaki/mangaki/tests/test_anidb.py, mangaki/mangaki/tests/test_anilist.py, mangaki/mangaki/utils/anidb.py, mangaki/mangaki/wrappers/anilist.py
- Fix a condition issue when checking the client availability (was `if not client_id and client_ver`)
- Test the `to_python_datetime` for both APIs
- Added a test case for when client's arguments are missing
- Use a fake client in tests (no need to use `[anidb]` or `[anilist]` settings section to test)
=> Improve tests for AniDB and AniList

mangaki/mangaki/admin.py, mangaki/mangaki/tests/test_anidb.py, mangaki/mangaki/tests/test_refresh_from_anidb.py, mangaki/mangaki/utils/anidb.py
Adresses an issue in the admin panel when two or more Works have the same AniDB identifiant and a `MultipleObjectsReturned` exception happens when refreshing the Work from AniDB.
Now, instead of having an error, no modifications are made and the user is alerted of that conflict !
*Also adds tests for refreshing data from AniDB from the admin panel*
=> Handle MultipleObjectsReturned when two Works have the same AniDB AID

mangaki/mangaki/admin.py, mangaki/mangaki/management/commands/anidb.py, mangaki/mangaki/models.py, mangaki/mangaki/tests/test_anidb.py, mangaki/mangaki/utils/anidb.py
In this PR, the goal is to improve the AniDB API wrapper :
- Move the `update_tags` method from `models.py` to `utils/anidb.py` (makes more sense)
- Create some methods to improve readability of the `get_or_update_work` method
- Reduce the amount of queries overall : improve the way staff is added to the database
- Clean the code for the wrapper slightly
=> Reduce the amount of queries in AniDB's API wrapper

mangaki/mangaki/management/commands/poster_neighbors.py, mangaki/setup.py, requirements/production.txt
Adds a `poster_neighbors` command which takes a Work ID as an argument (and an optional `--collage` argument) and prints the IDs of Works which posters are (supposedly) close to the one passed as an argument.
Example : `./manage.py poster_neighbors 1 --collage`
The optional `--collage` argument will create a collage of those posters in `static/image/posters_collages`.
This command actually takes up to 400MB of RAM on a single run, so another method to find neighbors for a poster might be better !
*Computing neighbors for a poster uses a `mangaki_i2v.json` JSON file in which tags for posters are stored, previously computed via [illustration2vec](http://illustration2vec.net/).*
=> Find neighbors of a poster

mangaki/mangaki/admin.py, mangaki/mangaki/templates/admin/merge_selected_confirmation.html, mangaki/mangaki/tests/test_merge.py
Closes #419 by correctly handling errors when merging works (ie. missing destination ID or missing required fields) instead of showing a 500 error page !
=> Correctly handle errors when merging works in admin

mangaki/mangaki/admin.py, mangaki/mangaki/management/commands/anidb.py, mangaki/mangaki/models.py, mangaki/mangaki/templates/admin/update_tags_via_anidb.html, mangaki/mangaki/tests/test_anidb.py, mangaki/mangaki/tests/test_refresh_from_anidb.py, mangaki/mangaki/utils/anidb.py
Closes #205 by improving the administration page for refreshing AniDB tags :
- Cleaner disposition
- Possibility to **modify the weight of tags** that were modified, added or kept by AniDB
- Possibility to **choose which works should have their tags updated** (after reviewing new tag information from AniDB)
- Possibility to **select which tags should be added, updated, kept or deleted** (by default, the checkboxes are checked meaning the planned operation will happen when submitting, given the work is marked for update)
Also moves the `Work.retrieve_tags` method to `utils/anidb/diff_between_anidb_and_local_tags`.
And no longer calls the API twice in order to only update 1 work !
=> Improved administration page for refreshing AniDB tags

mangaki/mangaki/admin.py, mangaki/mangaki/utils/anidb.py
This PR fixes issues with Artists and Staffs when refreshing from AniDB :
- Fixes an issue that could sometimes happen if the Staff object already exists
- Fixes an issue when an Artist has two or more roles on a single Work (closes #487)
And another fix that isn't really related :
+ Fixes an issue with TaggedWork objects when merging works
=> Fix error 500 for Staff objects when refreshing from AniDB

.gitignore, mangaki/mangaki/static/js/vote.js, mangaki/mangaki/templates/mangaki/work_rating.html
Le good first issue est un peu exagéré ici :)
Réussi à faire la modif dans work_rating.hml (cf la branche liée), ce qui fonctionne dans le cas hors mosaïque de recommandation.
Par contre n'étant que ultra débutant en Python j'ai du mal à voir où rajouter un mark_safe() sur le synopsis dans le cas d'une mosaïque de recommandation où les cartes sont chargées via l'API JS et via card.py, si vous avez des pistes je suis preneur ;)
Reference : #453
=> HTML is not escaped in Work's synopsis

README-fr.md, README.md, config.sh, provisioning/group_vars/mangaki_dev, provisioning/roles/mangaki_source/defaults/main.yml, provisioning/roles/mangaki_source/tasks/main.yml, provisioning/roles/utils/redis/handlers/main.yml, provisioning/roles/utils/redis/tasks/main.yml
As #498 lands on master, we should be able to use Celery for Vagrant powered instances.
=> Celery re-introduction for Vagrant with instructions!

mangaki/mangaki/models.py, mangaki/mangaki/templates/fix/fix_suggestion.html, mangaki/mangaki/views.py
Auto-fix is available only for NSFW/non-NSFW issues for now.
I am still thinking about the semantics of closing / re-opening a suggestion, if you auto fix a suggestion, then re-open it, what does it mean? The issue is already fixed, right?
=> Add auto-fix, re-open, close buttons to Mangaki Fix

provisioning/inventories/staging/host_vars/beta.mangaki.fr/vars.yml, provisioning/roles/mangaki_source/defaults/main.yml, provisioning/roles/mangaki_source/templates/settings.ini.j2, provisioning/roles/mangaki_web/README.md, provisioning/roles/mangaki_web/defaults/main.yml, provisioning/roles/mangaki_web/tasks/main.yml, provisioning/roles/utils/nginx_site/README.md, provisioning/roles/utils/nginx_site/templates/etc/nginx/sites-available/default.conf.j2
beta.mangaki.fr will be configured to use the optimal X-SendFile backend (NGINX) and will set an example to set up mangaki.fr for archives export.
=> GDPR compliancy — Step 2 (X-SendFile)

mangaki/mangaki/views.py
Search filters were providing pairs `(Work, WorkTitle)`, so duplicates.
In order to avoid the SQL error `SELECT DISTINCT ON expressions must match initial ORDER BY expressions`, `distinct` contains both `id` and `nb_ratings`, in order to order by popularity.
Fixes #574.
=> Ensure Work objects after search filter have distinct ID

mangaki/mangaki/admin.py, mangaki/mangaki/models.py, mangaki/mangaki/settings.py, mangaki/mangaki/tasks.py, mangaki/mangaki/templates/admin/merge_selected_confirmation.html, mangaki/mangaki/tests/test_merge.py, mangaki/mangaki/utils/mal.py, mangaki/mangaki/utils/work_merge.py, mangaki/setup.py, provisioning/roles/mangaki_source/tasks/main.yml, provisioning/roles/utils/celery/README.md, provisioning/roles/utils/celery/defaults/main.yml, provisioning/roles/utils/celery/tasks/main.yml, provisioning/roles/utils/celery/templates/etc/supervisor/conf.d/celery.conf.j2, requirements/production.txt
This PR introduces Celery Beat, a task scheduler which needs initial data migration (which are provided through `manage.py migrate`) and requires to run the beat worker of Celery. Finally, you have to go to the admin panel and configure the periodicity of `look_for_workclusters` (for debugging and instance-specific purpose).
~Depends on #533.~
=> Automatic Work Cluster from exact title match

mangaki/mangaki/admin.py, mangaki/mangaki/management/commands/merge.py, mangaki/mangaki/models.py, mangaki/mangaki/tests/test_merge.py, mangaki/mangaki/utils/work_merge.py
=> Compute difficulty of WorkCluster

mangaki/mangaki/admin.py
- `WorkCluster.origin` was a too big field to lookup
- `Suggestion` can be filtered by work or user
=> Improve SuggestionAdmin and WorkClusterAdmin

mangaki/mangaki/admin.py, mangaki/mangaki/models.py, mangaki/mangaki/settings.py, mangaki/mangaki/tests/test_change_default_title.py, mangaki/mangaki/tests/test_merge.py, mangaki/mangaki/tests/test_rating.py, mangaki/mangaki/tests/test_reco.py, mangaki/mangaki/tests/test_refresh_from_anidb.py, mangaki/mangaki/tests/test_research.py, mangaki/mangaki/urls.py, mangaki/mangaki/utils/archive_export.py, mangaki/mangaki/utils/recommendations.py, mangaki/mangaki/utils/work_merge.py, mangaki/mangaki/views.py, mangaki/mangaki/wrappers/anilist.py, requirements/dev.txt, requirements/production.txt
=> Bump Django 2.1.2, remove ColdStartRating

mangaki/mangaki/admin.py
But : faire de sorte que charger l'anime Goblin Slayer (beaucoup de tags) prenne moins de 8 s et 197 requêtes.
Actuellement : 6 s et 30 requêtes.
=> Reduce number of queries in admin for inline objects

requirements/production.txt
lxml is built with CPython, and older versions fail on Python 3.7.
=> requirements: update lxml to work with Python 3.7

mangaki/mangaki/migrations/0096_fix_mal_cdn.py, mangaki/mangaki/models.py
Fixes #653.
The migration is actually a reciprocal of [migrations/0071_fix_mal_cdn.py](https://github.com/mangaki/mangaki/blob/master/mangaki/mangaki/migrations/0071_fix_mal_cdn.py).
=> Put posters back ┬─┬ノ( º _ ºノ)

Vagrantfile, ansible.cfg, provisioning/roles/mangaki_source/tasks/main.yml, provisioning/roles/utils/celery/tasks/main.yml, provisioning/roles/utils/postgresql/tasks/main.yml
This mostly changes the Ansible configuration to be compatible with Vagrant:
- Use Debian Buster
- Enable pipelining in ansible.cfg
(see https://docs.ansible.com/ansible/latest/user_guide/become.html#risks-of-becoming-an-unprivileged-user )
- Use python3 for starting ansible on the host (default interpreter_python
in ansible.cfg)
- Some cleanup based on Ansible warnings (mostly stop using loops
for `apt`)
=> Fix Vagrant setup

poetry.lock, pyproject.toml
Markdown 3.3.5 fails tests, but not 3.3.4
python ^3.7.1 to match mangaki-zero
=> Updated Poetry requirements

nix/modules/mangaki.nix
This enables:
- regular migrations at each start
- clean up wrong assertions
=> Nix production setup migrations

flake.lock, flake.nix, nix/pkgs/mangaki/poetry-standard-overlay.nix, poetry.lock, pyproject.toml
nbconvert v7 is annoying to package because maintainers now downloads their CSS files at build-time, which breaks our model.
=> fix: drop Jupyter development dependency and fix Nix packaging
