- mangaki/mangaki/templates/index.html
> Update the URL to Mangaki's source code

- .editorconfig
- README.md
- Vagrantfile
- provisioning/playbook.yml
- provisioning/templates/secret.j2
- provisioning/vars/common.yaml
- provisioning/vars/db.yaml
- provisioning/vars/python.yaml
- requirements.yaml
Mangaki dans une VM pour Noël, c'est faisable!
Le provisionnement est fait par Ansible, j'admets qu'il faudrait rajouter NGINX et faire proxyfier le static. Parce que ça marche pas encore.
Related to #2.
(DO NOT MERGE)
> Environnement de développement Vagrant

- mangaki/frontend/src/components/Maintenance.js
Add the maintenance component related to the maintenance template
> Add the Maintenance template

- mangaki/mangaki/templates/mangaki/anime_detail.html
- mangaki/mangaki/templates/mangaki/manga_detail.html
Ceci change l'intitulé des boutons "Des idées pour améliorer cette fiche ?" en "Proposer une modification".
> Changement de l'intitulé du bouton « Des idées pour améliorer cette fiche ? »

- mangaki/mangaki/templates/mangaki/anime_detail.html
- mangaki/mangaki/views.py
Afin de conserver l'avis des gens qui ne l'ont pas vu, j'ai également ajouté
une ligne "XX% veulent le voir."
Fixes #39.
> Modifie les ratings affiché sur les statistiques

- mangaki/mangaki/templates/mangaki/anime_detail.html
- mangaki/mangaki/views.py
> Ajoute une statistique "X% l'ont vu"

- mangaki/mangaki/static/js/vote.js
> Remet les boutons opaques lors de l'annulation d'un vote

- mangaki/mangaki/static/js/autocomplete.js
- mangaki/mangaki/static/js/vote.js
Après le `===`, faisons un peu de `!something`.
> Réécrire les tests de variables nulles en JS

- mangaki/mangaki/templates/work_rating.html
Affiche "Je veux lire" / "Je ne veux pas lire" dans le poster d'un manga, et non pas "Je veux voir" / "Je ne veux pas voir".
> On ne regarde pas un manga

- mangaki/mangaki/templates/base.html
Des balises se trouvait après le </html>
> <script> after </html>

- mangaki/mangaki/admin.py
Afin de rendre l'affichage plus clair.
> Ajoute le nom de l'artiste dans l'admin des Tops

- mangaki/mangaki/templates/mangaki/anime_detail.html
- mangaki/mangaki/views.py
Par ailleurs si personne ne l'a vu ET il n'y a aucun willsee/wontsee, on n'affiche pas les statistiques.
> Affiche les willsee/wontsee dans les statistiques si personne n'a vu une oeuvre

- mangaki/mangaki/templates/mangaki/reco_list.html
Refais passer le bouton pour rafraichir les recommandations sous la liste quelque soit la largeur d'écran
> Recommandation list responsive

- mangaki/mangaki/views.py
- requirements.txt
Le tri des listes sur la page de profil n'est plus case sensitive.
fixes #106
> Correction du tri sur la page de profil

- mangaki/mangaki/templates/base.html
- mangaki/mangaki/templates/mangaki/anime_detail.html
- mangaki/mangaki/templates/mangaki/manga_detail.html
Ajout d'OpenGraph sur les page détails des mangas (pour le moment cela n'était que sur les animés)
Ajout d'une TwitterCard de type "summary" sur les page détails des mangas et des animés
> OpenGraph et Twittercards

- mangaki/mangaki/templates/events.html
Change meta description and declare that the contest is finished.
> Announce the winners

- mangaki/mangaki/static/js/autocomplete.js
- mangaki/mangaki/urls.py
- mangaki/mangaki/views.py
Ceci est une collection de 2 petits patches qui améliorent l'autocomplétion :
- Suppression de l'import automatique depuis MAL en cas d'échec de recherche (causait des doublons dans la BDD)
- Cesse de remplir automatiquement le LocalStorage avec des informations sur tous les animes/mangas.
> Améliore l'autocomplétion

- mangaki/mangaki/templates/pagination.html
> Add a letter parameter

- mangaki/mangaki/management/commands/addevents.py
- mangaki/mangaki/management/commands/analytics.py
- mangaki/mangaki/management/commands/anidb.py
- mangaki/mangaki/management/commands/animejoin.py
- mangaki/mangaki/management/commands/doctor.py
- mangaki/mangaki/management/commands/fetchposters.py
- mangaki/mangaki/management/commands/top.py
- mangaki/mangaki/management/commands/vgmdb.py
- mangaki/mangaki/utils/mal.py
- mangaki/mangaki/utils/recommendations.py
>  Enlève toute utilisation des classes Anime, Manga et Album

- mangaki/mangaki/views.py
> Make less queries when displaying events

- mangaki/mangaki/views.py
Reverts mangaki/mangaki#182
Lol, c'était déjà fait.
> Revert "Canonicalize work URLs"

- mangaki/mangaki/static/css/skin.css
- mangaki/mangaki/templates/mangaki/reco_list.html
- mangaki/mangaki/templates/mangaki/work_list.html
> Enable wrapping of text in big buttons

- mangaki/mangaki/static/css/skin.css
- mangaki/mangaki/templates/mangaki/reco_list.html
- mangaki/mangaki/templates/mangaki/work_list.html
> Improve line breaking in big buttons

- mangaki/mangaki/models.py
> Ajout d'un __str__ à Staff

- .editorconfig
- .eslintrc.json
- .gitattributes
- .gitignore
- .mailmap
- AUTHORS
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
- package.json
- requirements-dev.txt
Ceci rajoutera les bases pour aider les nouveaux membres à contribuer et à prendre les repères vis-à-vis des standards qu'on attend dans ce repo.
J'invite *tout le monde* à faire des changements (orthographique, sémantique, syntaxique, pratique), si tout le monde y met quelques lignes, ça peut faire sympathique. :)
Please review. :)
> Guidelines pour contribuer

- mangaki/mangaki/utils/knn.py
Après étude random du KNN (`utils/knn.py` et non `utils/recommendations.py` — utilisé dans `compare.py` en revanche), la somme des ratings (`sum_ratings`) n'est pas bien calculée.
En effet, si on regarde sur le diff, on voit:
```python
sum_ratings[work_id] = rating
```
Donc, ce n'est pas une somme.
Par conséquent, les moyennes sont faussés. 
Heureusement, l'impact sur la RMSE semble vraiment faible:
```console
[KNN] NB_NEIGHBORS = 20
RMSE 1.28…429885685
[KNN] NB_NEIGHBORS = 20
RMSE 1.27…776741366
```
Bien entendu, on ne veut pas d'un code qui ne marche pas comme on le souhaite.
P.S. : le `defaultdict` c'est pour nettoyer le nombre de `if` pour mettre une valeur par défaut, atroce.
> Réparer le KNN de compare (somme des ratings)

- mangaki/mangaki/management/commands/compare.py
- mangaki/mangaki/utils/nmf.py
- provisioning/bootstrap.sh
- requirements-dev.txt
> Fuck pandas.

- README.md
- circle.yml
- requirements-dev.txt
- requirements-linters.txt
- requirements-testing.txt
Partial feature towards #221 
We should be able to lint not only the last commit, but between master and branch being CI-ed commits.
(There is a PR in git-lint for this feature, wait & see.)
> Lint the last commit in the CI

- mangaki/mangaki/management/commands/compare.py
- requirements-dev.txt
> train_test_split moved in sklearn 0.18

- README.md
- mangaki/mangaki/models.py
Une petite modification pour bien commencer 2017.
> Fix path for Chiro and README

- mangaki/mangaki/management/commands/generate_seed_data.py
> Génération d'une seed (management command)

- mangaki/mangaki/templates/about.html
- mangaki/mangaki/templates/base.html
- mangaki/mangaki/templates/events.html
- mangaki/mangaki/templates/maintenance.html
- mangaki/mangaki/templates/mangaki/work_detail.html
- mangaki/mangaki/templates/profile.html
- mangaki/mangaki/templates/top.html
> Suppression des liens vers meta.mangaki.fr

- mangaki/mangaki/management/commands/compare.py
- mangaki/mangaki/templates/mangaki/reco_list.html
- mangaki/mangaki/urls.py
- mangaki/mangaki/utils/als.py
- mangaki/mangaki/utils/knn.py
- mangaki/mangaki/utils/recommendations.py
- mangaki/mangaki/utils/svd.py
- mangaki/mangaki/utils/wals.py
- mangaki/mangaki/views.py
Route `/reco/?category=anime&algo=svd` provides recommendations of anime using the SVD algorithm.
Fixes #263, #255 and #139.
> Add all recommendation algorithms to production

- mangaki/mangaki/management/commands/fit_algo.py
- mangaki/mangaki/utils/algo.py
- mangaki/mangaki/utils/als.py
- mangaki/mangaki/utils/chrono.py
- mangaki/mangaki/utils/data.py
- mangaki/mangaki/utils/recommendations.py
- mangaki/mangaki/utils/svd.py
- mangaki/mangaki/utils/wals.py
Ça devrait être plus clair comme ça ! J'en ai profité pour ajouter les requêtes dans Chrono et du coup les chrono.save sont moins illisibles comme ça.
Usage: `./mangaki/manage.py fit_algo (svd|als|wals)`
> Create Dataset class and fit_algo management command

- mangaki/mangaki/management/commands/compare.py
- mangaki/mangaki/utils/als.py
- mangaki/mangaki/utils/chrono.py
- mangaki/mangaki/utils/common.py
- mangaki/mangaki/utils/knn.py
- mangaki/mangaki/utils/pca.py
- mangaki/mangaki/utils/recommendations.py
- mangaki/mangaki/utils/svd.py
- mangaki/mangaki/utils/wals.py
> Add new class RecommendationAlgorithm and refactor algorithms

- mangaki/mangaki/admin.py
- mangaki/mangaki/models.py
- mangaki/mangaki/templates/admin/merge_selected_confirmation.html
- mangaki/mangaki/templates/admin/refresh_poster_confirmation.html
It's here!
- We should display a message if a choice is missing
- Maybe there are some other constraints that should be made because of the unique fields (see Rating and Staff)
- Sorry, the merging code is ugly, I don't know if it can be factored. I assume yes.
> Add an admin interface for merging works

- mangaki/mangaki/tests/test_rating.py
- mangaki/mangaki/utils/ratings.py
For some reason, one line was missing.
> [Hotfix] Toggling ratings (+test!)

- mangaki/mangaki/utils/recommendations.py
- mangaki/mangaki/views.py
To reproduce bug:
- Get SVD recommendations
- Delete one of those works
- Crash.
> [Hotfix] Handle recommended ghost works

- mangaki/mangaki/templates/base.html
> Ajout du meta description

- mangaki/mangaki/management/commands/tokens.py
- mangaki/mangaki/static/css/skin.css
- mangaki/mangaki/templates/research.html
- mangaki/mangaki/views.py
- requirements/production.txt
Usage:
- `./mangaki/manage.py tokens <username> research-kyoto-2017` returns a token
- `./mangaki/manage.py tokens DEBUG research-kyoto-2017` sends only to `DEBUG_USERNAMES`
- `./mangaki/manage.py tokens '*' research-kyoto-2017` sends to everyone
You will need to add a `newsletter.yaml` file in `DATA_DIR`:
subject: Mangaki organise un data challenge avec l'université de Kyoto
from: Jill-Jênn Vie <xxx@yyy.fr>
body: |
Bonjour {{ username }},
Mangaki va organiser un data challenge avec l'université de Kyoto !
...
https://mangaki.fr/research/?username={{ username }}&token={{ token }}
-- 
JJ, pour Mangaki
https://mangaki.fr
> Send templated mail with tokens

- mangaki/mangaki/templates/research.html
- mangaki/mangaki/views.py
> Fix sentence

- mangaki/mangaki/static/css/skin.css
- mangaki/mangaki/static/js/vote.js
- mangaki/mangaki/templates/mangaki/work_rating.html
Demo :  ![demo](https://user-images.githubusercontent.com/146210/27517588-56ead32e-59cf-11e7-8184-183e969d4db9.png)
Fixes #141
> Add ribbons displaying card category

- mangaki/mangaki/settings.py
Fixes Sentry reporting of views exception.
> Move to INFO and add console to the root handler

- mangaki/mangaki/templates/profile.html
Otherwise, anonymous profiles will not work.
> Hotfix: do not show recommendations tab on anonymous profiles

- .mailmap
- AUTHORS
- CHANGELOG.md
- mangaki/mangaki/templates/index.html
> Release 0.2

- mangaki/mangaki/views.py
> ranking ordered by score decreasingly

- mangaki/mangaki/models.py
- mangaki/mangaki/tests/test_anidb.py
- mangaki/tests/data/hibike_euphonium.xml
When adding different works from AniDB, it is possible that those works will have some tags in common.
By bulk adding those tags to the `Tag` database without checking if they are already there, an `IntegrityError` is almost certain to happen since the same `anidb_tag_id` will be added several times.
Therefore, we have to check before adding tags to the `Tag` database which tags are indeed new : **this PR adds one query to the `Work.update_tags` method but fixes that issue.**
> Fix an IntegrityError on Work.update_tags

- mangaki/mangaki/models.py
- mangaki/mangaki/tests/test_anidb.py
- mangaki/mangaki/utils/anidb.py
- mangaki/tests/data/anidb/aki_sora.xml
- mangaki/tests/data/anidb/astarotte_no_omocha_ex.xml
- mangaki/tests/data/anidb/bible_black.xml
- mangaki/tests/data/anidb/boku_no_piko.xml
- mangaki/tests/data/anidb/hibike_euphonium.xml
- mangaki/tests/data/anidb/panty_stocking.xml
- mangaki/tests/data/anidb/punchline.xml
- mangaki/tests/data/anidb/r15.xml
- mangaki/tests/data/anidb/sangatsu_no_lion.xml
- mangaki/tests/data/anidb/shimoneta.xml
Works are now flagged as NSFW based on their tags (see issue #382) ! Here's the principle :
- If the work is `restricted` on AniDB, it is flagged NSFW
- Else, tags are used to determine if it's potentially NSFW or not :
* Tags of **lower weight** (<= 400) are checked : if potentially NSFW tags consist of more than **30%** (*with weight taken into account*) of those tags, the work is flagged as NSFW
* Tags of **higher weight** (> 400) are checked : if more than **15%** of them (*with weight taken into account*) are potentially NSFW, the work is flagged as NSFW
*For now, potentially NSFW tags are stored in a list inside the `is_nsfw_based_on_tags` method : it might be interesting to store this kind of data in the `Tag` database, but it would add a query to check which tags are NSFW or not.*
> Flag works as NSFW based on AniDB tags

- mangaki/mangaki/admin.py
- mangaki/mangaki/templates/admin/change_default_work_title.html
- mangaki/mangaki/tests/test_change_default_title.py
- mangaki/mangaki/utils/anidb.py
Takes care of issue #370 by letting an admin chose which title is default on a Work !
> Change a Work's default title on admin side

- mangaki/mangaki/models.py
- mangaki/mangaki/utils/anidb.py
When some data is missing from AniDB, multiple issues could occur and make the code fail. This should fix most of these :
- Fix an issue when there are no tags retrieved
- Fix an issue when only the year is provided
- And other missing data
> Fix several issues when data is missing from AniDB

- mangaki/mangaki/admin.py
Fixes #416 (duplicate WorkCluster objects) and #424 (links towards phantom works are 404).
Regarding #416: do we need a WorkClusterCluster object? ;)
> Fix issues related to WorkCluster

- README.md
- circle.yml
- mangaki/mangaki/management/commands/top.py
- provisioning/roles/mangaki_back/README.md
- provisioning/roles/mangaki_back/handlers/main.yml
- provisioning/roles/mangaki_back/tasks/main.yml
> Add a --all argument to the top management command

- mangaki/mangaki/templates/base.html
> Add submenus to top categories in navigation bar

- mangaki/mangaki/views.py
Merci de merge cette PR dans les :
In [68]: (jj.date_joined.replace(hour=0, minute=0, second=0, microsecond=0) + timedelta(days=1001) - datetime.now(utc)).seconds
Out[68]: 30856
secondes.
> On Mangaki, I am 1000 days old!

- mangaki/mangaki/utils/recommendations.py
> Revert "Hotfix KNN on the stable branch"

- mangaki/mangaki/templates/mangaki/work_list.html
- mangaki/mangaki/templates/works.html
- mangaki/mangaki/tests/test_views.py
- mangaki/mangaki/views.py
> Redirect to a work's detail page if there's an unique search result

- mangaki/mangaki/admin.py
> Fix error 500 when searching TaggedWorks in admin

- mangaki/mangaki/templates/admin/merge_selected_confirmation.html
> Fix an issue with " in synopsis when merging works

- mangaki/mangaki/api/cards.py
- mangaki/mangaki/management/commands/ranking.py
- mangaki/mangaki/models.py
- mangaki/mangaki/templates/mangaki/work_list.html
- mangaki/mangaki/templates/profile.html
- mangaki/mangaki/utils/ranking.py
- mangaki/mangaki/views.py
> Add sort mode for pearls and flat mode

- requirements/dev.txt
> Requirement non à jour

- README-fr.md
- README.md
- config.sh
> Add README in English

- mangaki/mangaki/management/commands/unzip_algo.py
This should have been part of https://github.com/mangaki/mangaki/pull/464 but was forgotten.
(I had trouble finding it, actually it was only on the production machine 😲.)
> Add algo for unzipping on the production machine

- mangaki/mangaki/templates/events.html
- mangaki/mangaki/templates/mangaki/work_rating.html
- mangaki/mangaki/views.py
> Add featured works to events (Carrefour de l'animation 2017 !)

- mangaki/mangaki/templates/mangaki/work_list.html
- mangaki/mangaki/views.py
Minimal PR that will provide a lot of happiness.
Also shorten the titles so that it is less harmful on smartphones.
> Sort by recent works

- mangaki/mangaki/settings.py
- mangaki/mangaki/templates/base.html
- mangaki/mangaki/templatetags/version.py
- requirements/dev.txt
- requirements/production.txt
:rocket: with a link to the commit tree !
Fixes #432.
- Supports Git repository.
- Supports Egg packages (from PyPI / `setup.py`).
> Mangaki's version in the footer!

- mangaki/mangaki/views.py
> Search both title and alternative titles when searching a work

- mangaki/mangaki/utils/mal.py
Fix #524.
Maybe, I'll do a profile setting once #531 land on master.
**Disclaimer**: Unsure if it'll work with bigger MAL than mine. Should test later.
> Mark MAL as source of truth for further MAL imports

- mangaki/mangaki/algo/recommendation_algorithm.py
- mangaki/mangaki/algo/xals.py
- mangaki/mangaki/management/commands/fit_algo.py
- mangaki/mangaki/tests/test_algo.py
- mangaki/mangaki/tests/test_reco.py
- mangaki/mangaki/utils/recommendations.py
> Test recommendation endpoint and saving of snapshots

- mangaki/mangaki/algo/__init__.py
- mangaki/mangaki/algo/fma.py
- requirements/dev.txt
FMA = Factorization Machine = FullMetal Alchemist.
@RaitoBezarius va hurler, mais c'est pour le bien de tous.
> Add new recommendation algorithm FMA

- mangaki/mangaki/algo/__init__.py
- mangaki/mangaki/algo/als.py
- mangaki/mangaki/algo/als2.py
- mangaki/mangaki/algo/als3.py
- mangaki/mangaki/management/commands/compare.py
(ongoing)
Comprends pas pourquoi ALS2 est slightly better que ALS3 alors que c'est le même algo :o
> Add new ALS

- mangaki/mangaki/static/css/skin.css
- mangaki/mangaki/static/js/profile_settings.js
- mangaki/mangaki/templates/account/account_deleted.html
- mangaki/mangaki/templates/profile.html
- mangaki/mangaki/templates/profile_mal_importer.html
- mangaki/mangaki/templates/profile_preferences.html
- mangaki/mangaki/templates/profile_works.html
- mangaki/mangaki/tests/test_views.py
- mangaki/mangaki/urls.py
- mangaki/mangaki/views.py
- provisioning/inventories/staging/host_vars/beta.mangaki.fr/vars.yml
- provisioning/roles/mangaki_source/defaults/main.yml
- provisioning/roles/mangaki_source/templates/settings.ini.j2
- provisioning/roles/mangaki_web/README.md
- provisioning/roles/mangaki_web/defaults/main.yml
- provisioning/roles/mangaki_web/tasks/main.yml
- provisioning/roles/utils/nginx_site/README.md
- provisioning/roles/utils/nginx_site/templates/etc/nginx/sites-available/default.conf.j2
A bit more of polishing in step 4 for the account post-deletion page is planned.
> GDPR compliancy — Step 3 (frontend and account deletion)

- mangaki/mangaki/choices.py
- mangaki/mangaki/locale/fr/LC_MESSAGES/django.po
- mangaki/mangaki/locale/ja/LC_MESSAGES/django.po
- mangaki/mangaki/locale/zh-hant/LC_MESSAGES/django.po
- mangaki/mangaki/settings.py
- mangaki/mangaki/templates/about.html
- mangaki/mangaki/templates/base.html
- mangaki/mangaki/templates/events.html
- mangaki/mangaki/templates/fix/fix_index.html
- mangaki/mangaki/templates/index.html
- mangaki/mangaki/templates/mangaki/artist_list.html
- mangaki/mangaki/templates/mangaki/reco_list.html
- mangaki/mangaki/templates/mangaki/work_list.html
- mangaki/mangaki/templates/mangaki/work_rating.html
- mangaki/mangaki/templates/profile.html
- mangaki/mangaki/templates/top.html
- mangaki/mangaki/urls.py
- mangaki/mangaki/views.py
Si vous saviez le temps que ça m'a pris de comprendre que dans Django, on n'a plus zh comme clé mais zh-hant (pour simplifié).
> Add Chinese translation

- mangaki/mangaki/tests/test_algo.py
- mangaki/mangaki/tests/test_reco.py
- mangaki/mangaki/utils/recommendations.py
Hipsters == people who like anime that were not in the algorithm snapshot (pickle).
Fixes #562.
> Fix KNN reco for hipsters

- data/experiments/default.json
The interesting one is now in `mangaki/data/experiments/default.json`.
> Delete useless configuration file

- mangaki/mangaki/utils/singleton.py
- mangaki/mangaki/wrappers/anilist.py
- Fix related works construction ;
- Turn AniList into a true singleton class ;
- Rate limit signaling / auto-sleep
> Improve AniList API

- provisioning/roles/mangaki_sync/tasks/main.yml
Fixes #578. And repairs master.
> Fix path of compilemessages in Ansible

- mangaki/setup.py
- requirements/production.txt
> Bump Celery to 4.2

- mangaki/mangaki/admin.py
> Reduce number of queries in WorkCluster admin

- mangaki/mangaki/algo/recommendation_algorithm.py
- mangaki/mangaki/tests/test_mgt_commands.py
- Discounted Cumulative Gain
- Normalized Discounted Cumulative Gain
> Add DCG and NDCG to metrics for comparing algorithms

- mangaki/mangaki/algo/fma.py
- mangaki/mangaki/algo/side.py
- mangaki/mangaki/tests/test_algo.py
- Does not improve that much the performance (so far), unfortunately
- Helped me fix the `predict` method of `fma.py`
> Add poster tags to FMA algorithm

- mangaki/mangaki/algo/__init__.py
- mangaki/mangaki/algo/efm.py
- mangaki/mangaki/algo/ssvd.py
- requirements/dev.txt
1. ALS2 prend 23 s et RMSE = 1.134
2. ALS prend 14 s et RMSE = 1.143
3. Spotlight's SVD prend 198 s (lol) et RMSE = 1.334
4. Surprise's SVD prend 9 s et RMSE = 1.655
> Add Surprise and Spotlight SVD

- mangaki/mangaki/templates/profile_work.html
- mangaki/mangaki/views.py
From Alice :)
We have the view, so we should use it!
> Display cards in profile by default

- .circleci/config.yml
- provisioning/docker/Dockerfile
> CircleCI 2 — deployment to beta

- mangaki/setup.py
- requirements/production.txt
> Bump requirements

- mangaki/mangaki/views.py
What do you think? It just consists in filtering the WorkList by a username, to get their watchlist.
Particular case: I want to browse anime, but only within my watchlist.
(It is just a test.)
> Test: Filter WorkList by user watchlist

- provisioning/roles/mangaki_source/tasks/main.yml
> Add zero to initial requirements

- mangaki/mangaki/api/cards.py
- mangaki/mangaki/static/css/skin.css
- mangaki/mangaki/static/js/vote.js
- mangaki/mangaki/templates/mangaki/work_rating.html
> Add link to work in card and translate category even in mosaic

- mangaki/mangaki/utils/profile.py
- mangaki/mangaki/utils/recommendations.py
As the prototype changed, a new call had to be updated.
> Fix profile ordering

- mangaki/mangaki/urls.py
- mangaki/mangaki/views.py
Sinon ça renvoyait une erreur 500. On a supprimé le template mais pas la vue.
> Remove events from urls and views

- mangaki/mangaki/templates/account/login.html
Hop. Ça traînait depuis avril.
> Add login error message

- mangaki/mangaki/views.py
> シュタインズ・ゲートをβ世界線に直したよ

- .circle_mangaki_settings.ini
> Update port of CircleCI

- README-fr.md
- README.md
- mangaki/mangaki/models.py
Minimal PR that touches README and adds a comment.
> Remove DependencyCI

- mangaki/mangaki/templates/base.html
I fixed most page errors: https://validator.w3.org/nu/?doc=https%3A%2F%2Fmangaki.fr%2Fanime%2F
> Improve HTML validation

- mangaki/mangaki/templates/about.html
- mangaki/mangaki/templates/base.html
- mangaki/mangaki/templates/index.html
- mangaki/mangaki/templates/mangaki/legal.html
- mangaki/mangaki/templates/mangaki/reco_list.html
- mangaki/mangaki/templates/mangaki/work_list.html
Let's try to fix our broken SEO.
Also some pages have two h1 tags, for example in the preferences of the profile.
> Add missing h1 tags

- mangaki/mangaki/admin.py
> Fix admin search

- mangaki/mangaki/admin.py
> Fix Reference in admin

- mangaki/mangaki/templates/profile_preferences.html
> Add link to password reset

- mangaki/mangaki/utils/profile.py
> Fix unseen

- mangaki/mangaki/templates/base.html
> Improve SEO

- mangaki/mangaki/locale/fr/LC_MESSAGES/django.po
- mangaki/mangaki/locale/ja/LC_MESSAGES/django.po
- mangaki/mangaki/locale/zh_Hans/LC_MESSAGES/django.po
- mangaki/mangaki/locale/zh_Hant/LC_MESSAGES/django.po
- mangaki/mangaki/static/css/skin.css
- mangaki/mangaki/templates/mangaki/work_list.html
- mangaki/mangaki/templates/settings.html
- requirements/dev.txt
i faced issues running tests (just to get to know them) because any version after 2.9 changes time format 
i added that modification in dev.txt
closed issue #710
> fixing CSS in shortcut list and adding translation files + fixing psycopg2-binary to => 2.8, <2.9 for UTC

- .circleci/config.yml
Before @RaitoBezarius shows up let's forget about beta.
If I'm motivated I will create an alpha.mangaki.fr.
> Disable beta

- mangaki/mangaki/locale/fr/LC_MESSAGES/django.po
- mangaki/mangaki/templates/mangaki/reco_list.html
- mangaki/mangaki/templates/profile_friendlist.html
- mangaki/mangaki/utils/recommendations.py
- mangaki/mangaki/views.py
- Inédit pour moi (nouveau) / certaines / toutes
> Add new for me

- mangaki/mangaki/locale/fr/LC_MESSAGES/django.po
- mangaki/mangaki/templates/mangaki/reco_list.html
- mangaki/mangaki/tests/test_crypto.py
- mangaki/mangaki/tests/test_friend.py
- mangaki/mangaki/tests/test_reco.py
- mangaki/mangaki/utils/crypto.py
- mangaki/mangaki/utils/fit_algo.py
- mangaki/mangaki/utils/ratings.py
- mangaki/mangaki/utils/recommendations.py
- mangaki/mangaki/views.py
> Secure group recommendations

- mangaki/mangaki/api/urls.py
- mangaki/mangaki/api/user.py
- mangaki/mangaki/management/commands/fit_algo.py
- mangaki/mangaki/settings.py
- mangaki/mangaki/templates/base.html
- mangaki/mangaki/tests/test_rating.py
- mangaki/mangaki/tests/test_reco.py
- mangaki/mangaki/utils/fit_algo.py
- mangaki/mangaki/utils/ratings.py
- mangaki/mangaki/utils/viz.py
- mangaki/settings.template.ini
It is currently located at https://mangaki.fr/map/
> Add visualization map of embeddings

- mangaki/mangaki/utils/anidb.py
Ça faisait un bail que je n'avais pas fait de PR :)
> AniDB XML does not have URL anymore but it's trivial to make anyway

- CHANGELOG.md
With #707 merged, some breaking changes appeared, this is expected.
> Update changelog accordingly to breaking changes & new features

- .envrc
- .gitignore
- CHANGELOG.md
> Improve direnv performance with Nix Flakes

- .envrc
- .github/workflows/flakes-test.yml
- .gitignore
- CHANGELOG.md
> Enable end to end testing only if the PR has the complex label or on stable branch

- .circleci/config.yml
- README.md
- mangaki/mangaki/__init__.py
- mangaki/mangaki/api/urls.py
- mangaki/mangaki/api/user.py
- mangaki/mangaki/choices.py
- mangaki/mangaki/forms.py
- mangaki/mangaki/migrations/0088_auto_20171225_1534.py
- mangaki/mangaki/mixins.py
- mangaki/mangaki/models.py
- mangaki/mangaki/settings.py
- mangaki/mangaki/templates/faq/faq_index.html
- mangaki/mangaki/templates/fix/fix_index.html
- mangaki/mangaki/templates/fix/fix_suggestion.html
- mangaki/mangaki/templates/fix/nsfw_grid.html
- mangaki/mangaki/templates/mangaki/work_rating.html
- mangaki/mangaki/templatetags/posters.py
- mangaki/mangaki/tests/test_anilist.py
- mangaki/mangaki/tests/test_change_default_title.py
- mangaki/mangaki/tests/test_lookup_command.py
- mangaki/mangaki/tests/test_merge.py
- mangaki/mangaki/tests/test_mgt_commands.py
- mangaki/mangaki/tests/test_refresh_from_anidb.py
- mangaki/mangaki/urls.py
- mangaki/mangaki/utils/recommendations.py
- mangaki/mangaki/utils/viz.py
- mangaki/mangaki/views.py
- poetry.lock
- pyproject.toml
Here we go for one step of #766.
> Upgrade to Django 3

- mangaki/mangaki/tests/test_mgt_commands.py
- poetry.lock
- pyproject.toml
> Add dev dependencies and fix tests for Python 3.10

- mangaki/mangaki/admin.py
> Add Ref inline in Work admin
